some changes to the knife completions.. it may still be broken

diff --git a/_bash_knife-completion b/_bash_knife-completion
--- a/_bash_knife-completion
+++ b/_bash_knife-completion
@@ -1,127 +1,162 @@
-# vim: ft=sh:ts=4:sw=4:autoindent:expandtab:
-# Author: Avishai Ish-Shalom <avishai@fewbytes.com>
+#!/bin/bash
+#
+# Bash completion for Knife 0.10+
+#
 
-# We need to specify GNU sed for OS X, BSDs, etc.
-if [[ "$(uname -s)" == "Darwin" ]]; then
-    SED=gsed
+if [ $(uname) = "Darwin" ]; then
+    SED="gsed"
 else
-    SED=sed
+    SED="sed"
 fi
 
-# first argument set the command level
-_get_knife_completions() {
-    n=$1
-    shift
-    # first argument is knife, so shift it
-    #[ "$1" == "knife" ] && shift
-    local opts
-    opts="$($@ --help | grep -E '^knife' | cut -f$n -d" " | grep -v -E '[][[:upper:].]+' |grep -v '(options)')"
-    _upvar opts "$opts"
+_escape() {
+    echo "$1" | $SED -r s'/([^a-zA-Z0-9])/\\\1/g'
 }
 
-_flatten_knife_command() {
-    echo ${words[*]} |${SED} -r -e "s/\ *${words[$cword]}\$//" -e 's/\W/_/g'
+_flatten_command() {
+    local cur
+    _get_comp_words_by_ref cur
+    echo ${COMP_WORDS[*]} |  $SED -r -e 's/[[:space:]]-[[:alnum:]-]+//g' \
+        -e "s/[[:space:]]*$(_escape $cur)\$//" -e 's/[[:space:]]+/_/g'
 }
-# Check cache file for category ( passed as $1 ) and run command if cache is empty
-# Designed to be used with _get_knife_completions() and use the opts variables for options
-_completion_cache() {
-    local CACHE_DIR=${CHEF_HOME:-"$HOME/.chef"}/.completion_cache
-    local flag COMMAND
-    local OPTIND=1
-    while getopts "c" flag "$@"; do
-        case $flag in
-        c)
-            COMMAND=yes
-            ;;
-        *)
-            ;;
-        esac
-    done
-    shift $(( $OPTIND - 1 ))
 
-    local CACHE_FILE="$CACHE_DIR/$1"
-    shift
-    if [ ! -f "$CACHE_FILE" ]; then
-        if [[ "$COMMAND" == "yes" ]]; then
-            opts=$( eval $@ )
-        else
-            $@
-        fi
-        [ -d "$CACHE_DIR" ] && echo $opts >"$CACHE_FILE"
-    else
-        opts=$(cat "$CACHE_FILE")
-    fi
-    _upvar opts "$opts"
+# Helper functions to get lists of
+# Unfortunately knife pollutes STDOUT
+# on errors, making this more complicated then it needs to be.
+
+_output_on_success() {
+    local out
+    out=$($* 2>/dev/null)
+    [ $? -eq 0 ] && echo $out
+}
+
+_chef_nodes() {
+    _output_on_success knife node list
+}
+
+_chef_local_cookbooks() {
+    test -d cookbooks && find cookbooks -maxdepth 1 -type d -print0 | xargs -0 -n1 basename
+}
+
+_chef_remote_cookbooks() {
+    _output_on_success knife cookbook list | awk '{print $1}'
+}
+
+_chef_clients() {
+    _output_on_success knife client list
+}
+
+_chef_roles() {
+    _output_on_success knife role list
+}
+
+_chef_environemnts() {
+    _output_on_success knife environment list
+}
+
+_chef_data_bags() {
+    _output_on_success knife data bag list
+}
+
+_chef_data_bag_items() {
+    local bag
+    bag=$1
+    _output_on_success knife data bag show $bag
+}
+
+_chef_tags() {
+    local node
+    node=$1
+    _output_on_success knife tag list $node
 }
 
 _knife() {
-    local opts cur prev cword words flattened_knife_command
-    _completion_cache knife_commands _get_knife_completions 2 knife
-    _get_comp_words_by_ref cur prev cword words
-    flattened_knife_command=$(_flatten_knife_command)
-    COMPREPLY=()
-    case $flattened_knife_command in
-    *knife_cookbook_upload|*knife_cookbook_test)
-        local chef_repos
-        if [[ -z $CHEF_REPOS ]]; then
-            chef_repos=( $(${SED} -rn '/cookbook_path/ {s/.*\[(.*)\]/\1/g; s/[,'\'']//g; p}' ${CHEF_HOME:-"$HOME/.chef"}/knife.rb) )
-        else
-            chef_repos=( ${CHEF_REPOS[@]} )
-        fi
-        if [[ -n "$chef_repos" ]]; then
-            opts=$( ls -1p ${chef_repos[@]} | sort -u | ${SED} -n 's/\/$//p' )
-            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-        fi
-        ;;
-    *knife_data)
-        opts="bag"
-        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
+    local cur prev opts candidates
+    _get_comp_words_by_ref cur prev
+
+    opts="--server-url --key --color --config --defaults --editor \
+    --environment --format --no-color --no-editor --user --print-after \
+    --verbose --version --yes --help"
+
+    if [[ $cur == -* ]]; then
+        COMPREPLY=($(compgen -W "${opts}" -- ${cur}))
         return 0
-        ;;
-    *knife_node_show|*knife_node_edit|*knife_node_delete|*knife_tag_*)
-        _completion_cache -c knife_nodes "${words[0]} node list|${SED} -r -e 's/[\"\ ,]//g' -e '/[^0-9A-Za-z._-]+/d'"
-        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-        return 0
-        ;;
-    *knife_role_edit|*knife_role_show|*knife_role_delete)
-        _completion_cache -c knife_roles "${words[0]} role list|${SED} -r -e 's/[\"\ ,]//g' -e '/[^0-9A-Za-z._-]+/d'"
-        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-        return 0
-        ;;
-    *knife_data_bag_delete|*knife_data_bag_show|*knife_data_bag_edit)
-        _completion_cache -c knife_data_bags "${words[0]} data bag list|${SED} -r -e 's/[\"\ ,]//g' -e '/[^0-9A-Za-z._-]+/d'"
-        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-        return 0
-        ;;
-    *knife_data_bag_delete_*|*knife_data_bag_show_*|*knife_data_bag_edit_*)
-        _completion_cache -c knife_data_bag_$prev "${words[0]} data bag show $prev 2>/dev/null|${SED} -r -e 's/[\"\ ,]//g' -e '/^[^0-9A-Za-z._-]+/d'"
-        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-        return 0
-        ;;
-    *knife_client_list|*knife_client_show|*knife_client_edit)
-        _completion_cache -c knife_clients "${words[0]} client list|${SED} -r -e 's/[\"\ ,]//g' -e '/[^0-9A-Za-z._-]+/d'"
-        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-        return 0
-        ;;
-    *knife_environment_show|*knife_environment_edit|*knife_environment_delete)
-        _completion_cache -c knife_environments "${words[0]} environment list|${SED} -r -e 's/[\"\ ,]//g' -e '/[^0-9A-Za-z._-]+/d'"
-        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-        return 0
-        ;;
-    *)
-        case $cword in
-        1)
-            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-            return 0
+    fi
+
+    case $(_flatten_command) in
+        knife)
+            candidates="bootstrap client configure cookbook data_bag environment exec help index_rebuild node recipe role search ssh status tag"
+            ;;
+        knife_client)
+            candidates="create edit list reregister show delete bulk_delete"
+            ;;
+        knife_configure)
+            candidates="client"
+            ;;
+        knife_cookbook)
+            candidates="upload download metadata delete show create metadata bulk_delete test site"
+            ;;
+        knife_cookbook_site)
+            candidates="show install search share list unshare download"
+            ;;
+        knife_environment)
+            candidates="from_file delete show edit list create"
+            ;;
+        knife_data_bag)
+            candidates="delete create edit show list from_file"
+            ;;
+        knife_role)
+            candidates="edit show delete create from_file list bulk_delete"
+            ;;
+        knife_tag)
+            candidates="list delete create"
+            ;;
+        knife_node)
+            candidates="create run_list list from_file edit show delete bulk_delete"
+            ;;
+        knife_node_show|knife_node_edit|knife_node_delete)
+            candidates=$(_chef_nodes)
+            ;;
+        knife_node_run_list)
+            candidates="add remove"
+            ;;
+        knife_node_run_list_add|knife_node_run_list_remove)
+            candidates=$(_chef_nodes)
+            ;;
+        knife_client_show|knife_client_edit|knife_client_delete)
+            candidates=$(_chef_clients)
+            ;;
+        knife_cookbook_upload|knife_cookbook_test|knife_cookbook_metdata)
+            candidates=$(_chef_local_cookbooks)
+            ;;
+        knife_cookbook_download|knife_cookbook_delete|knife_cookbook_show)
+            candidates=$(_chef_remote_cookbooks)
+            ;;
+        knife_environment_delete|knife_environment_show|knife_environment_edit)
+            candidates=$(_chef_environments)
+            ;;
+        knife_data_bag_show|knife_data_bag_create|knife_data_bag_delete)
+            candidates=$(_chef_data_bags)
+            ;;
+        knife_data_bag_show_*|knife_data_bag_create_*|knife_data_bag_delete_*)
+            candidates=$(_chef_data_bag_items $prev)
+            ;;
+        knife_role_show|knife_role_edit|knife_role_delete)
+            candidates=$(_chef_roles)
+            ;;
+        knife_tag_create|knife_tag_list|knife_tag_delete)
+            candidates=$(_chef_nodes)
+            ;;
+        knife_tag_delete_*)
+            candidates=$(_chef_tags $prev)
             ;;
         *)
-            _completion_cache $flattened_knife_command  _get_knife_completions $(( $cword + 1 )) ${words[*]}
-            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
-            return 0
+            _filedir
+            return 0;
             ;;
-        esac
-        ;;
     esac
-    [[ ${#COMPREPLY[@]} -ge 1 ]] && return 0
+    COMPREPLY=($(compgen -W "${candidates}" -- ${cur}))
+    return 0
 }
+
 complete -F _knife knife
